version: '3.7'

networks:
  host_network:

services:
  dshex-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "dshex-bot"
    depends_on:
      - mongo
    volumes:
      - .:/dshex-bot

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /etc/data/db:/data/db
    networks:
      - host_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8080:8080"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
    networks:
      - host_network
